### ISSUE TITLE
Shortcut clash with Git Push

### ISSUE THREAD

**Issue by Petikoch** [leifhanack/intellijidea-shortcut-trainer#1]
Hi Leif,

thanks for this plugin, I like it!

I installed it into IntelliJ 14 and saw, that it's "Cmd-Shift-K / Ctrl-Shift-K" shortcut clashes with the very popular default "GIT PUSH" shortcut.

No big deal... since the shortcuts are configurable. 

But probably a hint for choosing a different shortcut as default for the shortcut-trainer?

Best regards,
Peti from Switzerland

**Comment by leifhanack** [comment]
Hi there, 

cool, someone is actual using it:)

Did you thought about creating a pull request on github? Which shortcut do you use?

Regards, Leif

**Comment by Petikoch** [comment]
Yes, I did think about a creating a pull request... but I don't know a reasonable default, therefore no pull request... :-)

I just used Alt-Ctrl-Shift-k for myself.
